services:
  - type: web
    name: stock-store
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stock-store-db
          property: connectionString

databases:
  - name: stock-store-db
    plan: free
    databaseName: stock_store
